"""
Copyright (c) 2017 Marco Aceti <dev@marcoaceti.it>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""


from pytrends.request import TrendReq
from config import *


import plotly.plotly as py
import plotly.graph_objs as go
import plotly

import os
import random
import string

import json

pytrend = TrendReq(GOOGLE_USERNAME, GOOGLE_PASSWORD, custom_useragent='test')
plotly.tools.set_credentials_file(username=PLOTLY_USERNAME, api_key=PLOTLY_API_KEY)


def graph(argument, country=None):
    trend_payload = {'q': argument}
    if country is not None:
        trend_payload = {'q': argument, 'geo': country}

    try:
        trend = pytrend.trend(trend_payload)
    except IndexError:
        return False

    x = []
    y = []
    for value in trend['table']['rows']:
        y += [value['c'][1]['v']]
        x += [value['c'][0]['v']]

    line = go.Scatter(
        x=x,
        y=y,
        name='Trend',
        line=dict(
            color='rgb(205, 12, 24)',
            width=1)
    )

    title = 'Google Trends: {q}. Generated by @{u}'.format(q=trend_payload['q'], u=BOT_USERNAME)
    layout = dict(title=title,
                  xaxis=dict(title='Date'),
                  yaxis=dict(title='Trend (100% is max peak)'),)

    filename = os.path.dirname(os.path.realpath(__file__)) + "/trend@{x}.png"\
        .format(x=''.join(random.choice(string.ascii_uppercase) for _ in range(9)))
    fig = dict(data=[line], layout=layout)
    py.image.save_as(fig, filename=filename)
    return filename


def process_message(update):
    message = update.message
    chat = update.chat
    usr = update.user
    bot = update.bot

    if usr.state() == 'trends1':
        msg = message.reply(usr.getstr('generating_graph'))
        file = graph(message.text)
        if not file:
            bot.api.call('editMessageText', {
                'chat_id': chat.id, 'message_id': msg.message_id, 'text': usr.getstr('trends_not_found'),
                'parse_mode': 'HTML', 'reply_markup':
                json.dumps(
                    {"inline_keyboard": [
                        [{"text": usr.getstr('back_button'), "callback_data": "home"}]
                    ]}
                )
            })
            usr.state('home')
            return True

        message.reply_with_photo(file)
        os.remove(file)  # Disk space is sacred
        msg.edit(usr.getstr('generated_graph'))

        usr.state('home')
        return True
